[book]
title = "xGov Beta Architecture"
authors = ["Algorand Foundation"]
description = "xGov Beta Architecture specifications and implementation"
multilingual = false
language = "en"
src = "docs"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "dark"
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/algorandfoundation/xgov-beta-sc"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/algorandfoundation/xgov-beta-sc/edit/main/{path}"
site-url = "https://xgov.algorand.co/"
additional-js = ["mermaid.min.js", "mermaid-init.js", "theme/sidebar-active-link.js"]

[output.html.fold]
enable = true
level = 3  # Navigation sidebar unfolded up to the 4th 0-based level. Tune it according to the max SUMMARY.md level depth.
