name: Preview xGov docs (PR)

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'SECURITY.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/docs-ci.yaml
    secrets: inherit

  preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    needs: [ validate ]
    if: ${{ !github.event.pull_request.draft }}
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}

      - name: Checkout source
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.52'

      - name: Install mdBook Mermaid
        run: cargo install mdbook-mermaid && mdbook-mermaid install .

      - name: Build docs
        run: mdbook build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./book

      - name: Deploy (PR Preview)
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          preview: true
