name: Release xGov docs

on:
  workflow_run:
    workflows: [ "Mainnet Stable Release xgov-beta-sc" ]
    types: [ completed ]

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  validate-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/docs-ci.yaml
    secrets: inherit

  deploy-docs:
    runs-on: ubuntu-latest
    needs: [ validate-docs ]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}

      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          submodules: recursive

      - name: Prepare mdBook output directory
        shell: bash
        run: |
          mkdir -p book
          chmod -R 777 book

      - name: Build mdBook
        run: docker compose run mdbook build

      - name: Deploy to Cloudflare Pages
        id: deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: xgov-beta-docs
          directory: book
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
